### ISSUE TITLE
pup_fede_cnd conda channel not found?

### ISSUE THREAD

**Issue by wmvanvliet** [MedMaxLab/selfEEG#2]
When attempting to install the package through conda, I get an error that the following URL cannot be resolved:  
`https://conda.anaconda.org/pup_fede_cnd/win-64/current_repodata.json`

Does that mean that the `pup_fede_cnd` channel does not exist?

**Comment by fedepup** [comment]
Sorry, there was a little typo in the command. The channel is "pup_fede_Cnd" . This is the reference link to the [anaconda](https://anaconda.org/Pup_Fede_Cnd/selfeeg) page. I will also change the description there. Thank you for having noticed the typo. Let me know if this solve the issue.

**Comment by wmvanvliet** [comment]
Ah, it's some weird issue with mamba. When I use plain conda, it indeed works.
